version: "3"
services:
  ################################
  #   Setup React-admin container
  ################################
  frontend:
    env_file:
      - ./env/.env.prod
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        REACT_APP_HOST_GRAPHAL: banlist.info
        REACT_APP_NODE_ENV: production
        REACT_APP_GOOGLE_CLIENT_ID: 480041338383-2nq6gjs7jqbov4b0ed1hd7tgkedh6l4r.apps.googleusercontent.com
        REACT_APP_FACEBOOK_APPID: 1227094848056324 
        REACT_APP_GITHUB_CLIENT_ID: 04e44718d32d5ddbec4c
        REACT_APP_GOOGLE_ANALYTICS4: G-M8LZ0N9TRY
        REACT_APP_SITE_TITLE: BERTHONG
        # REACT_APP_XXXX: ${REACT_APP_XXXX}
        REACT_APP_ENCRYPT_PASS: b9be11166d72e9e3ae7fd407165e4bd2
        REACT_APP_USER_ROLES: 62a2ccfbcf7946010d3c74a2,62a2ccfbcf7946010d3c74a6,62a2ccfbcf7946010d3c74a4
    ports:
      - "8011:80"
      - "443:443"
    volumes:
      - ./frontend/src:/app/src
      - ./uploads:/var/storage
    networks:
      - berthong
  ################################

  ################################
  #   Setup Api Graphql container
  ################################
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod   
    ports:
      # - "4001:4001"
      - "4000:4000"
    env_file:
      - ./env/.env.prod
    volumes:
      - ./uploads:/app/uploads  
    # environment:
    #   - MONGO_URI=mongodb://${MONGO_INITDB_USERNAME}:${MONGO_INITDB_PASSWORD}@mongo:${MONGO_PORT}/${MONGO_INITDB_DATABASE}?authMechanism=DEFAULT
    #   - RA_HOST=${RA_HOST}
    #   - GRAPHQL_PORT=${GRAPHQL_PORT}
    #   - JWT_SECRET=${JWT_SECRET}

    #   - GITHUB_URL_OAUTH_ACCESS_TOKEN=${GITHUB_URL_OAUTH_ACCESS_TOKEN}
    #   - GITHUB_URL_OAUTH_USER=${GITHUB_URL_OAUTH_USER}
    #   - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
    #   - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET} 
    networks:
      - berthong
  ################################

  ################################
  #   Setup Api Mongo and mongo-express container
  ################################
  mongo:
    image: mongo:6.0.1
    command: mongod --auth --port 29102
    expose:
      - 29102
    ports:
      - 29102:29102
    volumes:
      - ./mongo-single/data:/data/db
      - ./mongo-single/restore:/mongo-single/restore
      - ./mongo-single/mongod.conf:/etc/mongod.conf
      - ./restore:/home/restore
    restart: always
    networks:
      - berthong
networks:
  berthong:
    external: true 
    name: berthong-network
